name: Incidenthub-frontend

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  frontend-ci:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Build Docker image
        run: docker build -t incidenthub-frontend:ci .
